var namespaceWhiteCore_1_1CoreApplicationPlugins_1_1RegionModulesController =
[
    [ "RegionModulesControllerPlugin", "d7/d63/classWhiteCore_1_1CoreApplicationPlugins_1_1RegionModulesController_1_1RegionModulesControllerPlugin.html", "d7/d63/classWhiteCore_1_1CoreApplicationPlugins_1_1RegionModulesController_1_1RegionModulesControllerPlugin" ]
];